services:
    arangodb:
        image: arangodb
        container_name: arangodb
        environment:
            - ARANGO_ROOT_PASSWORD=test123
        ports:
            - "8529:8529"
        volumes:
            - arangodb_data:/var/lib/arangodb3
            - ./data:/data

volumes:
    arangodb_data:
        driver: local
