version: "3.8"

services:
    neo4j:
        image: neo4j:5.25.1-community
        container_name: neo4j
        ports:
            - "7474:7474"
            - "7687:7687"
        environment:
            NEO4J_AUTH: neo4j/12345678
        volumes:
            - ./neo4j_data:/data
            - ./neo4j_logs:/logs
            - ./neo4j_import:/var/lib/neo4j/import
            - ./neo4j_plugins:/plugins
